name=Arduino HTTPServer Advanced
version=0.1.0
author=Jeffrey Becker
maintainer=Jeffrey Becker <jeffrey.a.becker@gmail.com>
sentence=A general-purpose HTTP server library for Arduino-compatible boards independent of the underlying platform
paragraph=This library provides a simple HTTP server implementation for Arduino-compatible boards, allowing them to serve web pages and handle HTTP requests handling multiple connections simultaniously
category=Communication
url=https://github.com/jeffreyabecker/Arduino-HTTPServer
architectures=*
dot_a_linkage=true
