name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1
    
    - name: Install Raspberry Pi Pico core
      run: |
        arduino-cli core install -b rp2040:rp2040
    
    - name: Build sketch
      run: |
        arduino-cli compile -b rp2040:rp2040:rpipico src/main.cpp
